### ISSUE TITLE
点云上采样

### ISSUE THREAD

**Issue by LiXiangDeng** [liuxinhai/L2G-AE#1]
您好 我注意到您的论文里提到您提出的该模型可以用于点云上采样 我想跑一下您的模型在PU1K数据集上的效果 注意到您的代码似乎只给了用于分割的代码 不知道您是否可以提供用来点云上采样的代码 十分感谢

**Comment by liuxinhai** [comment]
你好，L2G-AE中的上采样是无监督的，所以其实就是用的特征表示学习的网络，做法就是把重建的局部点云拉出来，做一个降采样就是上采样的结果了。希望有帮助！
________________________________
发件人: 邓清水 ***@***.***>
发送时间: 2022年8月4日 8:20
收件人: liuxinhai/L2G-AE ***@***.***>
抄送: Subscribed ***@***.***>
主题: [liuxinhai/L2G-AE] 点云上采样 (Issue #1)


您好 我注意到您的论文里提到您提出的该模型可以用于点云上采样 我想跑一下您的模型在PU1K数据集上的效果 注意到您的代码似乎只给了用于分割的代码 不知道您是否可以提供用来点云上采样的代码 十分感谢

―
